"""Cross-platform safety checks and filesystem mutation primitives."""

from safe_fs_ops.filesystem_ops.backend import (
    FilesystemBackendCapabilities,
    FilesystemOperationCapability,
    UnsupportedFilesystemBackendError,
    custom_backend_capabilities,
    detect_default_backend_capabilities,
)
from safe_fs_ops.filesystem_ops.backups import (
    BackupContentMismatchError,
    RestoreConflictError,
    capture_backup,
    restore_backup,
)
from safe_fs_ops.filesystem_ops.capture_directories import (
    CapturedDirectoryOwnershipClass,
    CapturedDirectoryRecord,
    capture_directory_to_quarantine,
    cleanup_captured_directory,
    restore_captured_directory,
)
from safe_fs_ops.filesystem_ops.content_addressed import ContentAddressedPutResult, ContentAddressedStore
from safe_fs_ops.filesystem_ops.models import (
    BackupFileType,
    ContentRef,
    FileBackup,
    FileType,
    PathSafety,
    ResourceSnapshot,
    TreeBackup,
    TreeBackupEntry,
    TreeBackupEntryKind,
)
from safe_fs_ops.filesystem_ops.mutations import (
    AtomicWriteHooks,
    DeleteHooks,
    DurabilityMode,
    MakeDirectoryHooks,
    ParentChangedAfterMutationError,
    UnsupportedFilesystemMutationError,
    atomic_write_bytes,
    atomic_write_text,
    delete_file,
    make_directory,
)
from safe_fs_ops.filesystem_ops.paths import (
    UnsafePathError,
    ensure_safe_delete_path,
    ensure_safe_mkdir_path,
    ensure_safe_parent_chain,
    ensure_safe_write_path,
    inspect_path,
)
from safe_fs_ops.filesystem_ops.remove_directories import (
    DirectoryIdentity,
    IdentitySafeRemoveDirectoryUnavailableError,
    RemoveDirectoryHooks,
    identity_safe_remove_directory_unavailable_reason,
    remove_empty_directory,
    remove_existing_empty_directory_by_identity,
)
from safe_fs_ops.filesystem_ops.renames import (
    RenamedFileType,
    RenameRecord,
    rename_no_replace,
    restore_inverse_rename,
)
from safe_fs_ops.filesystem_ops.snapshot_bundles import HashPolicy, SnapshotBundle, SnapshotBundleEntry, snapshot_bundle
from safe_fs_ops.filesystem_ops.snapshots import SnapshotHooks, UnsupportedFilesystemSnapshotError, snapshot_resource
from safe_fs_ops.filesystem_ops.tree_backups import (
    TreeRestoreConflictPolicy,
    backup_tree,
    restore_tree_backup,
    tree_backup_from_journal_payload,
)

__all__ = [
    "BackupContentMismatchError",
    "BackupFileType",
    "CapturedDirectoryOwnershipClass",
    "CapturedDirectoryRecord",
    "FilesystemBackendCapabilities",
    "FilesystemOperationCapability",
    "HashPolicy",
    "ContentAddressedStore",
    "ContentAddressedPutResult",
    "ContentRef",
    "FileBackup",
    "FileType",
    "PathSafety",
    "ResourceSnapshot",
    "RenamedFileType",
    "RenameRecord",
    "RestoreConflictError",
    "SnapshotBundle",
    "SnapshotBundleEntry",
    "SnapshotHooks",
    "TreeBackup",
    "TreeBackupEntry",
    "TreeBackupEntryKind",
    "TreeRestoreConflictPolicy",
    "UnsupportedFilesystemBackendError",
    "UnsafePathError",
    "AtomicWriteHooks",
    "DeleteHooks",
    "DurabilityMode",
    "MakeDirectoryHooks",
    "ParentChangedAfterMutationError",
    "DirectoryIdentity",
    "IdentitySafeRemoveDirectoryUnavailableError",
    "RemoveDirectoryHooks",
    "UnsupportedFilesystemMutationError",
    "UnsupportedFilesystemSnapshotError",
    "atomic_write_bytes",
    "atomic_write_text",
    "backup_tree",
    "capture_backup",
    "capture_directory_to_quarantine",
    "cleanup_captured_directory",
    "custom_backend_capabilities",
    "delete_file",
    "detect_default_backend_capabilities",
    "ensure_safe_delete_path",
    "ensure_safe_mkdir_path",
    "ensure_safe_parent_chain",
    "ensure_safe_write_path",
    "inspect_path",
    "make_directory",
    "remove_empty_directory",
    "remove_existing_empty_directory_by_identity",
    "rename_no_replace",
    "restore_captured_directory",
    "restore_backup",
    "restore_inverse_rename",
    "restore_tree_backup",
    "identity_safe_remove_directory_unavailable_reason",
    "snapshot_bundle",
    "snapshot_resource",
    "tree_backup_from_journal_payload",
]
